### ISSUE TITLE
jshell (jdk) compatibility issue

### ISSUE THREAD

**Issue by stoneasher** [Apress/java-for-absolute-beginners#3]
Hello ,

i have installed jdk-11.0.9_windows-x64_bin.exe as recommended by the book .
but when i go to run the following code stated in the book  :
```
jshell> String createHello(String s){
...> return "Hello " + s;
...> }
| created method createHello(String)
jshell> createHello(text)
$8 ==> "Hello this is a text"
| created scratch variable $8 : String
```

**it doesn't work** it gives this result instead :
```
jshell> createHello(text)
|  Error:
|  cannot find symbol
|    symbol:   variable text
|  createHello(text)
|              ^--^
```

any clue ??

the book has many incompatibility issues :( , that is for beginners doesn't explain which should we use strictly java 11 or what ? or stay with latest version available on the oracle website ? i am confused .

**Comment by stoneasher** [comment]
i downloaded 10 edition of jdk and its working fine .

**Comment by iuliana** [comment]
Hello @stoneasher, 

I am sorry you experienced troubles.  I've recompiled the sources multiple times, with multiple JDKs. The project is quite stable and I am determined to keep it so. So if I receive feedback about stuff not working I usually solve it pretty fast. 

What you are showing there is a command executed with jshell. I have no control over that. There might have been something wrong with the JDK. 

I am glad you found a solution though. Please create issues if you find any other bugs and send me an email for any feedback you have on book. It will be useful for the next edition.  

Have fun learning Java. Cheers!
